// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _NetWebApi.Data;

namespace _NetWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210124203101_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("_NetWebApi.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            mail = "aaa@aa.com",
                            nome = "Lauro"
                        },
                        new
                        {
                            id = 2,
                            mail = "bbb@aa.com",
                            nome = "Roberto"
                        },
                        new
                        {
                            id = 3,
                            mail = "ccc@aa.com",
                            nome = "Ronaldo"
                        },
                        new
                        {
                            id = 4,
                            mail = "ddd@aa.com",
                            nome = "Rodrigo"
                        },
                        new
                        {
                            id = 5,
                            mail = "eee@aa.com",
                            nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("_NetWebApi.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("desconto")
                        .HasColumnType("REAL");

                    b.Property<int>("pedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("produtoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("valor")
                        .HasColumnType("REAL");

                    b.Property<double>("valorFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("valorUni")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("pedidoId");

                    b.HasIndex("produtoId");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            id = 1,
                            desconto = 0.0,
                            pedidoId = 1,
                            produtoId = 1,
                            quantidade = 2,
                            valor = 2.2000000000000002,
                            valorFinal = 2.2000000000000002,
                            valorUni = 1.1000000000000001
                        },
                        new
                        {
                            id = 2,
                            desconto = 0.5,
                            pedidoId = 1,
                            produtoId = 2,
                            quantidade = 1,
                            valor = 2.0,
                            valorFinal = 1.5,
                            valorUni = 2.0
                        },
                        new
                        {
                            id = 3,
                            desconto = 1.0,
                            pedidoId = 1,
                            produtoId = 3,
                            quantidade = 1,
                            valor = 3.5,
                            valorFinal = 2.5,
                            valorUni = 3.5
                        },
                        new
                        {
                            id = 4,
                            desconto = 0.0,
                            pedidoId = 2,
                            produtoId = 1,
                            quantidade = 2,
                            valor = 2.2000000000000002,
                            valorFinal = 2.2000000000000002,
                            valorUni = 1.1000000000000001
                        },
                        new
                        {
                            id = 5,
                            desconto = 1.0,
                            pedidoId = 2,
                            produtoId = 3,
                            quantidade = 4,
                            valor = 14.0,
                            valorFinal = 13.0,
                            valorUni = 3.5
                        },
                        new
                        {
                            id = 6,
                            desconto = 2.0,
                            pedidoId = 3,
                            produtoId = 2,
                            quantidade = 5,
                            valor = 10.0,
                            valorFinal = 8.0,
                            valorUni = 2.0
                        });
                });

            modelBuilder.Entity("_NetWebApi.Models.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("clienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("data")
                        .HasColumnType("TEXT");

                    b.Property<double>("desconto")
                        .HasColumnType("REAL");

                    b.Property<double>("valor")
                        .HasColumnType("REAL");

                    b.Property<double>("valorFinal")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("clienteId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            clienteId = 1,
                            data = "01",
                            desconto = 1.0,
                            valor = 0.0,
                            valorFinal = 0.0
                        },
                        new
                        {
                            id = 2,
                            clienteId = 3,
                            data = "04",
                            desconto = 0.0,
                            valor = 0.0,
                            valorFinal = 0.0
                        },
                        new
                        {
                            id = 3,
                            clienteId = 4,
                            data = "14",
                            desconto = 5.0,
                            valor = 0.0,
                            valorFinal = 0.0
                        });
                });

            modelBuilder.Entity("_NetWebApi.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("preco")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Macarrão",
                            preco = 1.1000000000000001
                        },
                        new
                        {
                            id = 2,
                            nome = "Feijão",
                            preco = 2.0
                        },
                        new
                        {
                            id = 3,
                            nome = "Azeitona",
                            preco = 3.5
                        });
                });

            modelBuilder.Entity("_NetWebApi.Models.Item", b =>
                {
                    b.HasOne("_NetWebApi.Models.Pedido", "pedido")
                        .WithMany("Itens")
                        .HasForeignKey("pedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_NetWebApi.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("_NetWebApi.Models.Pedido", b =>
                {
                    b.HasOne("_NetWebApi.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("_NetWebApi.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
